### ISSUE TITLE
NeuronBlocks installation problem

### ISSUE THREAD

**Issue by 2019zhou** [microsoft/Unithon#2]
For the installation step
``` pip install -r requirements.txt ```
The installation fails for *Could not find a version that satisfies the requirements*

The solution on baidu that is replace the command with
 ``` pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.1-cp36-cp36m-win_amd64.whl  ```
does not work either saying that *torch-0.4.1  is not a supported wheel on this platform*

Group LastMinute zhouzhou

**Comment by xybai** [comment]
Could you share your error log? Which package you cannot install? If the error is something like, could not find some version, you can change the version your server can find in the requirements.txt file.
Besides, for the pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.1-cp36-cp36m-win_amd64.whl, please make sure that the whl file you select is consistent with your server environment, e.g., cuda90, cp36

**Comment by xybai** [comment]
> For the installation step
> `pip install -r requirements.txt`
> The installation fails for _Could not find a version that satisfies the requirements_
> 
> The solution on baidu that is replace the command with
> `pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.1-cp36-cp36m-win_amd64.whl `
> does not work either saying that _torch-0.4.1 is not a supported wheel on this platform_
> 
> Group LastMinute zhouzhou

Could you share your error log? Which package you cannot install? If the error is something like, could not find some version, you can have a try to change the version your server can find in the requirements.txt file.
Besides, for the "pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.1-cp36-cp36m-win_amd64.whl", please make sure that the whl file you select is consistent with your server environment, e.g., cuda90, cp36

**Comment by 2019zhou** [comment]
The error log is that
Cannot find a version that satisfies the requirements ftfy == 5.5.1
![image](https://user-images.githubusercontent.com/52394242/79627845-676ffe80-816e-11ea-8ba4-e9046265c02f.png)
Thanks a lot for your suggestion, we will try them out.
